version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    # Run it at a specific time so that we don't get emails all day long
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    # GitHub actions are using git tags (v1 = v1.2 = v1.2.3) which should be compatible until a major change is performed
    update-types: 
    - "version-update:semver-minor"
    - "version-update:semver-patch"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    # Run it at a specific time so that we don't get emails all day long
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "org.yaml:snakeyaml"
    # Version 2+ requires Spring Boot 3
    versions: ">=2.0.0"
  - dependency-name: "org.springframework.boot:*"
    # Version 3+ requires Vaadin 24
    versions: ">=3.0.0"
  - dependency-name: "com.vaadin:*"
    versions: ">=24.0.0"
